import Head from 'next/head'
import Image from 'next/image'
import { Button, TextInput } from '@mantine/core';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [walkImage, setWalkImage] = useState('')
  const [imageSearch, setImageSearch] = useState('')

  // Grab Image API Link from Search Query
  const grabArtLink = async () => {
    console.log('Grabbing api link...')
    try {
      const response = await fetch('/api/grabImageLink', {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify( {query: imageSearch})
      });
  
      const data = await response.json();
      
      // Validate API call was succesfully made.
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`)
      }
  
       grabArtDisplay(data.result)
  
        } catch (error) {
  
          // Additional error handling beyond unsucessful api call
          
        }
  };

  // Grab Actual Image Based on Query
  const grabArtDisplay = async (api_link) => {
    console.log('Grabbing display...')
    try {
      const response = await fetch('/api/grabImageDisplay', {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify( {link: api_link})
      });
      const data = await response.json();
      
      // Validate API call was succesfully made.
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`)
      }
  
        console.log(data)
        setWalkImage(data.result)
  
        } catch (error) {
  
          // Additional error handling beyond unsucessful api call
          
        }
  };

  return (
    <>
      <Head>
        <title>Art Walk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Image fill src={walkImage} alt="n/a"></Image>
        <div className={styles.center}>
        <TextInput
      placeholder="Example: Cats"
      label="What are you looking for?"
      description="(Enter an attribute of a piece you'd like to see)"
      withAsterisk
      value={imageSearch}
      onChange={(event) => setImageSearch(event.currentTarget.value)}
    />
        <Button 
        color="teal"
        onClick={grabArtLink}
        >
          Walk
        </Button>
          
        </div>

        <div className={styles.grid}>
         
        </div>
      </main>
    </>
  )
}
