import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@mantine/core';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [walkImage, setWalkImage] = useState('')

  const grabArt = async () => {

    try {
      const response = await fetch('/api/hello', {
        method: "GET",
        headers: {}
      });
  
      const data = await response.json();
      
      // Validate API call was succesfully made.
      if (response.status !== 200) {
        throw data.error || new Error(`Request failed with status ${response.status}`)
      }
  
        console.log(data)
        setWalkImage(data.result)
  
        } catch (error) {
  
          // Additional error handling beyond unsucessful api call
          
        }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Image fill src={walkImage} alt="n/a"></Image>
        <div className={styles.center}>
        <Button 
        color="teal"
        onClick={grabArt}
        >
          Walk
        </Button>
          
        </div>

        <div className={styles.grid}>
         
        </div>
      </main>
    </>
  )
}
